"""Update databse Model

Revision ID: c205f44c9c93
Revises: 7a03ef5d9cb0
Create Date: 2024-11-18 19:14:33.975637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c205f44c9c93'
down_revision = '7a03ef5d9cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
